name: Build

on:
  push:
    branches:
      - release

jobs:

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        env:
          CIBW_SKIP: '*_i686 *musllinux* pp* cp27-* cp33-* cp34-* cp35-* cp310-*'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install twine
        run: |
          python -m pip install twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.BPOSD_PYPI_PASSWORD }}
        run: |
          twine upload ./wheelhouse/*

